---
- name: Clone environment repository to temporary path
  git:
    repo: "{{ remote_repo }}"
    dest: "{{ checkout_path }}"
    update: yes
  tags:
    git

- name: Create Conda environment from project environment file.
  command: "{{conda_root}}/{{conda_folder_name}}/bin/conda env update"
  args:
    chdir: "{{ project_location }}"
  tags:
    conda

- name: Ensure destination dir exists
  file:
    path: "{{ install_root }}"
    state: directory

- name: Install package
  shell: "python setup.py clean && python setup.py install --prefix {{ install_root }}"
  args:
    chdir: "{{ checkout_path }}"



