name: agdc
dependencies:
- numpy
- scipy
- numexpr
- pandas
- gdal >=1.9
- netcdf4
- xarray
- dask
- distributed
- click
- pyyaml
- sqlalchemy
- python-dateutil
- jsonschema
- singledispatch
- psycopg2
- future
- matplotlib
- jupyter
- shapely
- fiona
- cython
- rasterio >=0.34
- rtree
- ephem
- geopandas
- pathlib2
- folium
- scikit-learn
- scikit-image
- psutil
- pytables
- flask
- bottleneck
- mkl-service
- glueviz
- ffmpeg
- pip
- pip:
  - pathlib
  - cachetools
  - pypeg2
  - plotly

