name: agdc
dependencies:
- basemap
- bottleneck
- cartopy
- click
- cython
- dask
- distributed
- ephem
- ffmpeg
- fiona
- flask
- folium
- future
- gdal >=1.9
- geopandas
- glueviz
- gunicorn
- ipdb
- jplephem
- jsonschema
- jupyter
- jupyter_contrib_nbextensions
- line_profiler
- luigi
- matplotlib
- memory_profiler
- mkl-service
- mock
- netcdf4
- numexpr
- numpy
- pandas
- pathlib2
- pep8
- pip
- psutil
- psycopg2
- pylint
- pytables
- pytest
- pytest-cov
- python-dateutil
- pyyaml
- rasterio >=0.34
- rtree
- scikit-image
- scikit-learn
- scipy
- seaborn
- shapely
- singledispatch
- sqlalchemy
- tqdm
- xarray
- pip:
  - cachetools
  - ciso8601
  - pathlib
  - plotly
  - pypeg2
  - skyfield
  - yappi

