- name: Ensure {{modules_path}}/modulefiles/{{module_name}} exists
  file: path={{modules_path}}/modulefiles/{{module_name}} state=directory

- name: Create modulefile
  template:
    src: module_template.j2
    dest: "{{modules_path}}/modulefiles/{{module_name}}/{{module_version}}"
    mode: 0660
